const sessions = [
  { number: 1, date: 'Friday, 2 October 2026', day: 'Friday', time: '6:00 PM–7:15 PM PKT', end: '7:30 PM–8:45 PM PKT', title: 'Foundations — Qubits, Gates & Superposition', type: 'talk', tag: 'Event 1', speaker: 'Dustin Rippe; Dr. Fatima Bint e Munir' },
  { number: 2, date: 'Saturday, 3 October 2026', day: 'Saturday', time: '6:00 PM–8:30 PM PKT', end: '', title: 'Measurement, Circuits & Qiskit Patterns', type: 'talk', tag: 'Event 2', speaker: 'Saad Ejaz' },
  { number: 3, date: 'Sunday, 4 October 2026', day: 'Sunday', time: '6:00 PM–8:30 PM PKT', end: '', title: 'Multi-Qubit Circuits & Entanglement', type: 'talk', tag: 'Event 3', speaker: 'Dr. Fatima Bint e Munir' },
  { number: 4, date: 'Friday, 9 October 2026', day: 'Friday', time: '6:00 PM–8:30 PM PKT', end: '', title: 'Circuit Optimization & Transpilation', type: 'talk', tag: 'Event 4', speaker: 'Dustin Rippe' },
  { number: 5, date: 'Saturday, 10 October 2026', day: 'Saturday', time: '6:00 PM–7:15 PM PKT', end: '7:30 PM–8:45 PM PKT', title: 'Noise, Backends & Real Hardware', type: 'talk', tag: 'Event 5', speaker: 'Dustin Rippe; Muhammad Khizar' },
  { number: 6, date: 'Sunday, 11 October 2026', day: 'Sunday', time: '6:00 PM–7:45 PM PKT', end: '8:00 PM–8:45 PM PKT', title: 'Dynamic Circuits & Parameterized Circuits', type: 'talk', tag: 'Event 6', speaker: 'Dr. Fatima Bint e Munir; Fatima Shahzadi' },
  { number: 7, date: 'Thursday, 15 October 2026', day: 'Thursday', time: '12:00 PM–4:00 PM PKT', end: '', title: 'LAB 1', type: 'workshop', tag: 'LAB 1', speaker: 'Noor Ul Ain' },
  { number: 8, date: 'Friday, 16 October 2026', day: 'Friday', time: '9:00 AM–1:00 PM PKT', end: '', title: 'LAB 2', type: 'workshop', tag: 'LAB 2', speaker: 'Noor Ul Ain' },
  { number: 9, date: 'Sunday, 18 October 2026', day: 'Sunday', time: '2:00 PM–6:00 PM PKT', end: '', title: 'Hackathon', type: 'connect', tag: 'Hackathon', speaker: 'All Guest Speakers' }
];
const scheduleList = document.querySelector('#scheduleList');
const filterButtons = document.querySelectorAll('[data-filter]');
function renderSchedule(filter = 'all') { scheduleList.innerHTML = sessions.filter((session) => filter === 'all' || session.type === filter).map((session, index) => `<article class="schedule-row ${index === 1 ? 'highlight-row' : ''}"><div class="schedule-time"><strong>${session.time}</strong>${session.end ? `<span>${session.end}</span>` : ''}</div><div class="schedule-info"><span class="session-tag tag-${session.type}">${session.tag}</span><h3>${session.title}</h3><p><strong>Tentative Date:</strong> ${session.date} • <strong>Day:</strong> ${session.day} • <strong>Time:</strong> ${session.time}${session.end ? ` / ${session.end}` : ''} • <strong>Speaker/Instructor:</strong> ${session.speaker}</p></div><span class="schedule-arrow">↗</span></article>`).join(''); }
renderSchedule();
filterButtons.forEach((button) => button.addEventListener('click', () => { filterButtons.forEach((item) => item.classList.remove('active')); button.classList.add('active'); renderSchedule(button.dataset.filter); }));
const mobileMenu = document.querySelector('#mobileMenu');
const nav = document.querySelector('#mainNav');
mobileMenu.addEventListener('click', () => { nav.classList.toggle('is-open'); mobileMenu.querySelector('span').textContent = nav.classList.contains('is-open') ? '×' : '+'; });
nav.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => nav.classList.remove('is-open')));
const API_BASE = window.API_BASE_URL || 'http://localhost:4000/api';
const accountTrigger = document.querySelector('#accountTrigger');
const accountOverlay = document.querySelector('#accountOverlay');
const accountClose = document.querySelector('#accountClose');
const authView = document.querySelector('#authView');
const accountView = document.querySelector('#accountView');
const authForm = document.querySelector('#authForm');
const authMessage = document.querySelector('#authMessage');
const nameField = document.querySelector('#nameField');
const accountTitle = document.querySelector('#accountTitle');
const authSubmit = document.querySelector('#authSubmit');
const authModes = document.querySelectorAll('[data-auth-mode]');
let authMode = 'login';
function setAuthMode(mode) { authMode = mode; authModes.forEach((button) => button.classList.toggle('active', button.dataset.authMode === mode)); const signup = mode === 'signup'; nameField.hidden = !signup; nameField.querySelector('input').required = signup; accountTitle.innerHTML = signup ? 'Join the<br /><em>community.</em>' : 'Welcome<br /><em>back.</em>'; authSubmit.innerHTML = signup ? 'Create account <span>↗</span>' : 'Log in <span>↗</span>'; authMessage.textContent = ''; }
function showAccountPanel() { accountOverlay.hidden = false; document.body.classList.add('account-open'); if (localStorage.getItem('qiskitToken')) loadCurrentUser(); }
function closeAccountPanel() { accountOverlay.hidden = true; document.body.classList.remove('account-open'); }
function authHeaders() { return { Authorization: `Bearer ${localStorage.getItem('qiskitToken')}` }; }
function showAuthError(message) { authMessage.textContent = message; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character]); }
async function loadCurrentUser() { try { const response = await fetch(`${API_BASE}/auth/me`, { headers: authHeaders() }); if (!response.ok) throw new Error('Session expired.'); const { user } = await response.json(); authView.hidden = true; accountView.hidden = false; accountTrigger.innerHTML = `${user.role === 'admin' ? 'Admin' : 'Account'} <span>↗</span>`; document.querySelector('#accountRoleLabel').textContent = user.role === 'admin' ? 'ADMIN CONSOLE' : 'MEMBER ACCESS'; document.querySelector('#accountGreeting').innerHTML = 'Hello,<br /><em></em>'; document.querySelector('#accountGreeting em').textContent = `${user.name.split(' ')[0]}.`; document.querySelector('#accountStatus').textContent = user.role === 'admin' ? 'You have administrator access.' : 'Your account is ready for event updates and submissions.'; const data = document.querySelector('#accountData'); if (user.role === 'admin') await loadAdminData(data); else { const submissionsResponse = await fetch(`${API_BASE}/submissions/me`, { headers: authHeaders() }); const submissions = submissionsResponse.ok ? (await submissionsResponse.json()).submissions : []; data.innerHTML = `<span class="mono">${user.email}</span><strong>${submissions.length} submission${submissions.length === 1 ? '' : 's'}</strong><small>Your data is private to your account.</small>`; } } catch { localStorage.removeItem('qiskitToken'); authView.hidden = false; accountView.hidden = true; accountTrigger.innerHTML = 'Log in <span>↗</span>'; } }
async function loadAdminData(container) { const [usersResponse, submissionsResponse] = await Promise.all([fetch(`${API_BASE}/admin/users`, { headers: authHeaders() }), fetch(`${API_BASE}/admin/submissions`, { headers: authHeaders() })]); if (!usersResponse.ok || !submissionsResponse.ok) throw new Error('Admin data unavailable.'); const users = (await usersResponse.json()).users; const submissions = (await submissionsResponse.json()).submissions; container.innerHTML = `<div class="admin-stat"><strong>${users.length}</strong><small>USERS</small></div><div class="admin-stat"><strong>${submissions.length}</strong><small>SUBMISSIONS</small></div><div class="admin-items"><b>Recent interest</b>${submissions.slice(0, 4).map((item) => `<span>${escapeHtml(item.email)}<small>${escapeHtml(item.status)}</small></span>`).join('') || '<small>No submissions yet.</small>'}</div>`; }
accountTrigger.addEventListener('click', showAccountPanel); accountClose.addEventListener('click', closeAccountPanel); accountOverlay.addEventListener('click', (event) => { if (event.target === accountOverlay) closeAccountPanel(); }); authModes.forEach((button) => button.addEventListener('click', () => setAuthMode(button.dataset.authMode)));
document.querySelector('#logoutButton').addEventListener('click', () => { localStorage.removeItem('qiskitToken'); authView.hidden = false; accountView.hidden = true; accountTrigger.innerHTML = 'Log in <span>↗</span>'; setAuthMode('login'); });
authForm.addEventListener('submit', async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(authForm)); const endpoint = authMode === 'signup' ? 'signup' : 'login'; authSubmit.disabled = true; try { const response = await fetch(`${API_BASE}/auth/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Authentication failed.'); localStorage.setItem('qiskitToken', result.token); authForm.reset(); await loadCurrentUser(); } catch (error) { showAuthError(error.message); } finally { authSubmit.disabled = false; } });
setAuthMode('login');
function updateCountdown() { const target = new Date('2026-10-01T09:00:00'); const diff = Math.max(target - new Date(), 0); document.querySelector('#days').textContent = String(Math.floor(diff / 86400000)).padStart(2, '0'); document.querySelector('#hours').textContent = String(Math.floor((diff / 3600000) % 24)).padStart(2, '0'); document.querySelector('#minutes').textContent = String(Math.floor((diff / 60000) % 60)).padStart(2, '0'); }
updateCountdown(); setInterval(updateCountdown, 60000);
const revealObserver = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add('visible'); }), { threshold: 0.14 });
document.querySelectorAll('.reveal, .principles > div, .experience-card, .speaker-placeholder').forEach((element) => revealObserver.observe(element));
