const sessions = [
  { number: 1, tag: 'Day 1', filterKey: 'day-1', type: 'talk', date: '2 October 2026', day: 'Friday', time: '6:00 PM–7:15 PM PKT', end: '7:30 PM–8:45 PM PKT', title: 'Foundations — Qubits, Gates & Superposition', formLink: 'https://forms.gle/WNx5xcZ9uoygQLXt6', speaker: 'Dustin Rippe; Dr. Fatima Bint-e-Munir', speakerTopics: [
    { name: 'Dustin Rippe', topics: ['Introduction to Quantum Computing', 'Python environment setup for Qiskit 2.x', 'Vectors, matrices and inner products', 'Qiskit Statevector and Operator'] },
    { name: 'Dr. Fatima Bint-e-Munir', topics: ['Single-qubit gates: X, H, Z, Y, S, T', 'Superposition'] }
  ] },
  { number: 2, tag: 'Day 2', filterKey: 'day-2', type: 'talk', date: '3 October 2026', day: 'Saturday', time: '6:00 PM–8:30 PM PKT', end: '', breakNote: 'Break: 7:15 PM–7:30 PM PKT', title: 'Measurement, Circuits & Qiskit Patterns', formLink: 'https://forms.gle/NCrChB2qh49ey5Zo9', speaker: 'Saad Ejaz', topics: ['Measurement', 'Bloch sphere visualization', 'Introduction to state tomography', 'Qiskit Patterns: Map, Optimize, Execute, Post-process', 'Sampler Primitive', 'Estimator Primitive'] },
  { number: 3, tag: 'Day 3', filterKey: 'day-3', type: 'talk', date: '4 October 2026', day: 'Sunday', time: '6:00 PM–8:30 PM PKT', end: '', breakNote: 'Break: 7:15 PM–7:30 PM PKT', title: 'Multi-Qubit Circuits & Entanglement', formLink: 'https://forms.gle/g9JkxJLBYn6qrKd58', speaker: 'Dr. Fatima Bint-e-Munir', topics: ['Multi-qubit state representation', 'Tensor products', 'Entanglement and lab demonstration', 'Bell states', 'GHZ states'] },
  { number: 4, tag: 'Day 4', filterKey: 'day-4', type: 'talk', date: '9 October 2026', day: 'Friday', time: '6:00 PM–8:30 PM PKT', end: '', breakNote: 'Break: 7:15 PM–7:30 PM PKT', title: 'Circuit Optimization & Transpilation', formLink: 'https://forms.gle/ryrEfxhZbJrDyzsXA', speaker: 'Dustin Rippe', topics: ['Circuit depth: what it is and why it matters', 'Reducing depth: fan-out vs. chain; recursive fan-out', 'Transpilation deep dive', 'GHZ optimization: fan-out, chain, recursive', 'Heavy-Hex topology'] },
  { number: 5, tag: 'Day 5', filterKey: 'day-5', type: 'talk', date: '10 October 2026', day: 'Saturday', time: '6:00 PM–7:15 PM PKT', end: '7:30 PM–8:45 PM PKT', title: 'Noise, Backends & Real Hardware', formLink: 'https://forms.gle/4sJUiqQUecVndv839', speaker: 'Dustin Rippe; Muhammad Khizar', speakerTopics: [
    { name: 'Dustin Rippe', topics: ['Noise in quantum computers: types of noise and sources', 'Noisy simulation', 'Noise models: depolarization, Pauli, thermal'] },
    { name: 'Muhammad Khizar', topics: ['Quantum microprocessor (advanced topic)', 'Backend properties: T1, T2, gate errors, readout errors'] }
  ] },
  { number: 6, tag: 'Day 6', filterKey: 'day-6', type: 'talk', date: '11 October 2026', day: 'Sunday', time: '6:00 PM–7:45 PM PKT', end: '8:00 PM–8:45 PM PKT', title: 'Dynamic Circuits & Parameterized Circuits', formLink: 'https://forms.gle/QKHtyFNgtkfAwwai9', speaker: 'Dr. Fatima Bint-e-Munir; Fatima Shahzadi', speakerTopics: [
    { name: 'Dr. Fatima Bint-e-Munir', topics: ['Classical registers', 'Mid-circuit measurement', 'Conditional logic', 'Dynamic circuits: step-by-step explanation'] },
    { name: 'Fatima Shahzadi', topics: ['Parameter and ParameterVector', 'Real-world quantum applications'] }
  ] },
  { number: 7, tag: 'Day 7 — Hackathon', filterKey: 'hackathon', type: 'connect', date: '25 October 2026', day: 'Sunday', time: '2:00 PM–6:00 PM PKT', end: '', title: 'Hackathon & Project Day', speaker: 'All Guest Speakers', topics: ['Hackathon tips & tricks', 'Hackathon project work & presentations', 'Lab Notebooks', 'Presentation Slides'] },
  { number: 8, tag: 'Lab 1', filterKey: 'lab-1', type: 'workshop', date: '17 October 2026', day: 'Saturday', time: '6:00 PM–9:00 PM PKT', end: '', title: 'Lab 1', formLink: 'https://forms.gle/to4D7AD8BP3RGX1S9', speaker: 'Noor-Ul-Ain' },
  { number: 9, tag: 'Lab 2', filterKey: 'lab-2', type: 'workshop', date: '18 October 2026', day: 'Sunday', time: '6:00 PM–9:00 PM PKT', end: '', title: 'Lab 2', formLink: 'https://forms.gle/zhUJbseW5fYBgiaE7', speaker: 'Noor-Ul-Ain' }
];
const scheduleList = document.querySelector('#scheduleList');
const filterButtons = document.querySelectorAll('[data-filter]');
function topicsMarkup(session) { if (session.speakerTopics) return session.speakerTopics.map((group) => `<p class="topic-speaker"><strong>${group.name}:</strong></p><ul class="schedule-topics">${group.topics.map((topic) => `<li>${topic}</li>`).join('')}</ul>`).join(''); if (session.topics) return `<ul class="schedule-topics">${session.topics.map((topic) => `<li>${topic}</li>`).join('')}</ul>`; return ''; }
function arrowMarkup(session) { return session.formLink ? `<a class="schedule-arrow" href="${session.formLink}" target="_blank" rel="noopener noreferrer" aria-label="Open registration form">↗</a>` : `<span class="schedule-arrow">↗</span>`; }
function renderSchedule(filter = 'all') { scheduleList.innerHTML = sessions.filter((session) => filter === 'all' || session.filterKey === filter).map((session, index) => `<article class="schedule-row ${index === 1 ? 'highlight-row' : ''}"><div class="schedule-time"><strong>${session.time}</strong>${session.end ? `<span>${session.end}</span>` : ''}</div><div class="schedule-info"><span class="session-tag tag-${session.type}">${session.tag}</span><h3>${session.title}</h3><p><strong>Tentative Date:</strong> ${session.date} • <strong>Day:</strong> ${session.day} • <strong>Time:</strong> ${session.time}${session.end ? ` / ${session.end}` : ''}${session.breakNote ? ` • <strong>${session.breakNote}</strong>` : ''} • <strong>Speaker/Instructor:</strong> ${session.speaker}</p>${topicsMarkup(session)}</div>${arrowMarkup(session)}</article>`).join(''); }
renderSchedule();
filterButtons.forEach((button) => button.addEventListener('click', () => { filterButtons.forEach((item) => item.classList.remove('active')); button.classList.add('active'); renderSchedule(button.dataset.filter); }));
const mobileMenu = document.querySelector('#mobileMenu');
const nav = document.querySelector('#mainNav');
mobileMenu.addEventListener('click', () => { nav.classList.toggle('is-open'); mobileMenu.querySelector('span').textContent = nav.classList.contains('is-open') ? '×' : '+'; });
nav.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => nav.classList.remove('is-open')));
const API_BASE = window.API_BASE_URL || 'http://localhost:4000/api';
const accountTrigger = document.querySelector('#accountTrigger');
const accountOverlay = document.querySelector('#accountOverlay');
const accountClose = document.querySelector('#accountClose');
const authView = document.querySelector('#authView');
const accountView = document.querySelector('#accountView');
const authForm = document.querySelector('#authForm');
const authMessage = document.querySelector('#authMessage');
const nameField = document.querySelector('#nameField');
const accountTitle = document.querySelector('#accountTitle');
const authSubmit = document.querySelector('#authSubmit');
const authModes = document.querySelectorAll('[data-auth-mode]');
let authMode = 'login';
function setAuthMode(mode) { authMode = mode; authModes.forEach((button) => button.classList.toggle('active', button.dataset.authMode === mode)); const signup = mode === 'signup'; nameField.hidden = !signup; nameField.querySelector('input').required = signup; accountTitle.innerHTML = signup ? 'Join the<br /><em>community.</em>' : 'Welcome<br /><em>back.</em>'; authSubmit.innerHTML = signup ? 'Create account <span>↗</span>' : 'Log in <span>↗</span>'; authMessage.textContent = ''; }
function showAccountPanel() { accountOverlay.hidden = false; document.body.classList.add('account-open'); if (localStorage.getItem('qiskitToken')) loadCurrentUser(); }
function closeAccountPanel() { accountOverlay.hidden = true; document.body.classList.remove('account-open'); }
function authHeaders() { return { Authorization: `Bearer ${localStorage.getItem('qiskitToken')}` }; }
function showAuthError(message) { authMessage.textContent = message; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character]); }
async function loadCurrentUser() { try { const response = await fetch(`${API_BASE}/auth/me`, { headers: authHeaders() }); if (!response.ok) throw new Error('Session expired.'); const { user } = await response.json(); authView.hidden = true; accountView.hidden = false; accountTrigger.innerHTML = `${user.role === 'admin' ? 'Admin' : 'Account'} <span>↗</span>`; document.querySelector('#accountRoleLabel').textContent = user.role === 'admin' ? 'ADMIN CONSOLE' : 'MEMBER ACCESS'; document.querySelector('#accountGreeting').innerHTML = 'Hello,<br /><em></em>'; document.querySelector('#accountGreeting em').textContent = `${user.name.split(' ')[0]}.`; document.querySelector('#accountStatus').textContent = user.role === 'admin' ? 'You have administrator access.' : 'Your account is ready for event updates and submissions.'; const data = document.querySelector('#accountData'); if (user.role === 'admin') await loadAdminData(data); else { const submissionsResponse = await fetch(`${API_BASE}/submissions/me`, { headers: authHeaders() }); const submissions = submissionsResponse.ok ? (await submissionsResponse.json()).submissions : []; data.innerHTML = `<span class="mono">${user.email}</span><strong>${submissions.length} submission${submissions.length === 1 ? '' : 's'}</strong><small>Your data is private to your account.</small>`; } } catch { localStorage.removeItem('qiskitToken'); authView.hidden = false; accountView.hidden = true; accountTrigger.innerHTML = 'Log in <span>↗</span>'; } }
async function loadAdminData(container) { const [usersResponse, submissionsResponse] = await Promise.all([fetch(`${API_BASE}/admin/users`, { headers: authHeaders() }), fetch(`${API_BASE}/admin/submissions`, { headers: authHeaders() })]); if (!usersResponse.ok || !submissionsResponse.ok) throw new Error('Admin data unavailable.'); const users = (await usersResponse.json()).users; const submissions = (await submissionsResponse.json()).submissions; container.innerHTML = `<div class="admin-stat"><strong>${users.length}</strong><small>USERS</small></div><div class="admin-stat"><strong>${submissions.length}</strong><small>SUBMISSIONS</small></div><div class="admin-items"><b>Recent interest</b>${submissions.slice(0, 4).map((item) => `<span>${escapeHtml(item.email)}<small>${escapeHtml(item.status)}</small></span>`).join('') || '<small>No submissions yet.</small>'}</div>`; }
accountTrigger.addEventListener('click', showAccountPanel); accountClose.addEventListener('click', closeAccountPanel); accountOverlay.addEventListener('click', (event) => { if (event.target === accountOverlay) closeAccountPanel(); }); authModes.forEach((button) => button.addEventListener('click', () => setAuthMode(button.dataset.authMode)));
document.querySelector('#logoutButton').addEventListener('click', () => { localStorage.removeItem('qiskitToken'); authView.hidden = false; accountView.hidden = true; accountTrigger.innerHTML = 'Log in <span>↗</span>'; setAuthMode('login'); });
authForm.addEventListener('submit', async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(authForm)); const endpoint = authMode === 'signup' ? 'signup' : 'login'; authSubmit.disabled = true; try { const response = await fetch(`${API_BASE}/auth/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Authentication failed.'); localStorage.setItem('qiskitToken', result.token); authForm.reset(); await loadCurrentUser(); } catch (error) { showAuthError(error.message); } finally { authSubmit.disabled = false; } });
setAuthMode('login');
function updateCountdown() { const target = new Date('2026-10-01T09:00:00'); const diff = Math.max(target - new Date(), 0); document.querySelector('#days').textContent = String(Math.floor(diff / 86400000)).padStart(2, '0'); document.querySelector('#hours').textContent = String(Math.floor((diff / 3600000) % 24)).padStart(2, '0'); document.querySelector('#minutes').textContent = String(Math.floor((diff / 60000) % 60)).padStart(2, '0'); }
updateCountdown(); setInterval(updateCountdown, 60000);
const revealObserver = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add('visible'); }), { threshold: 0.14 });
document.querySelectorAll('.reveal, .principles > div, .experience-card, .speaker-placeholder').forEach((element) => revealObserver.observe(element));
